# Generated by Django 6.0.4 on 2026-04-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='month',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
