# Generated by Django 6.0.4 on 2026-04-29 10:00

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_habitrecord_unique_together_habitrecord_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='month',
            field=models.IntegerField(default=tracker.models.current_month),
        ),
        migrations.AddField(
            model_name='habit',
            name='year',
            field=models.IntegerField(default=tracker.models.current_year),
        ),
    ]
