# Generated by Django 6.0.4 on 2026-04-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_habit_month_habit_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitrecord',
            unique_together={('habit', 'day', 'month', 'year')},
        ),
    ]
